# Generated by Django 5.1.6 on 2025-03-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmFlowApp', '0003_remove_user_last_login_remove_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='slot',
        ),
        migrations.AddField(
            model_name='seat',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FilmFlowApp.schedule'),
        ),
    ]
