# Generated by Django 5.1.6 on 2025-03-02 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmFlowApp', '0005_alter_seat_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilmFlowApp.slot')),
            ],
        ),
    ]
