# Generated by Django 5.1.6 on 2025-03-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmFlowApp', '0007_remove_schedule_slot_remove_slot_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='film',
        ),
        migrations.AddField(
            model_name='session',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FilmFlowApp.film'),
        ),
    ]
