# Generated by Django 5.1.6 on 2025-03-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmFlowApp', '0008_remove_schedule_film_session_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FilmFlowApp.session'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FilmFlowApp.schedule'),
        ),
    ]
