# Generated by Django 5.1.6 on 2025-03-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmFlowApp', '0011_alter_slot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
